spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1_schema?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: zl202897mq
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIDle: ture
#    testOnBorrow: false
#    testReturn: false
#    poolPrepareStalements: true
##   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙\
#    filters: stat,wall
#    maxPoolPreparaedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: ture
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址： https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500



  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#server:
#  port:8181